name: backend_comisiones
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.1.0
  dart_frog_cors: ^2.0.0
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  mysql_client: ^0.0.27

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
